<?php
namespace app\jzadmin\controller\app;

use app\jzadmin\controller\Common;

class App extends Common
{
    protected $appModel;

    public function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->appModel=model("App");
    }

    /**
     * 应用列表管理
     */
    public function index(){
        $param = $this->request->param();
        $keyword = isset ($param ['keyword']) ? addSlashesFun($param ['keyword']) : "";
        $where = array();
        if (!empty ($keyword)) {
            $where ['appid'] = array('like', '%' . $keyword . '%');
        }
        $request = array('status');
        foreach ($request as $value) {
            $status = isset ($param [$value]) ? $param [$value] : "";
            if ($status != "") {
                $where [$value] = $status;
                $this->assign($value, $status);
            }
        }
        $noteList = $this->appModel->where($where)->order("id desc")->paginate(20, false, array("query" => $param));
        return $this->fetch('', array('keyword' => $keyword, 'list' => $noteList, 'page' => $noteList->render()));
    }

    /**
     * 添加应用
     */
    public function  add(){
        if ($this->request->isPost()){
            $addResult=$this->appModel->createAppData($this->request->post());
            if ($addResult){
                $this->success("添加成功");
            }else{
                $this->error("添加失败：".$this->appModel->getError());
            }

        }else{
            return $this->fetch('add',array('method'=>'add'));
        }
    }

    /**
     * 修改应用
     */
    public function edit(){
        $param=$this->request->param();
        $id=isset($param['id']) ? intval($param['id']) : 0;
        if (empty($id))
            $this->error("参数错误");
        if ($this->request->isPost()){
            $addResult=$this->appModel->createAppData($this->request->post());
            if ($addResult){
                $this->success("修改成功");
            }else{
                $this->error("修改失败：".$this->appModel->getError());
            }
        }else{
            $info=$this->appModel->where("id",$id)->limit(1)->find();
            return $this->fetch('add',array('method'=>'edit','info'=>$info));
        }
    }

    /**
     * 删除应用
     */
    public function del(){
        $param=$this->request->param();
        $id=isset($param['id']) ? intval($param['id']) : 0;
        if (empty($id))
            $this->error("参数错误");
        $result=$this->appModel->where("id",$id)->delete();
        if ($result){
            $this->success("删除成功");
        }else{
            $this->error("删除失败");
        }
    }

}